Фадеев Сергей Викторович M3335
CPP-KT/signal_task pull request #17
Opened 2020-10-30 20:12 UTC by FadeevSergey

2020-11-02 11:11 UTC, hazzus requested changes

2020-11-02 11:11 UTC, hazzus commented on CMakeLists.txt
> +cmake_minimum_required(VERSION 3.13.4)
[minor] Зачем?)

2020-11-02 11:11 UTC, hazzus commented on signals.h
> +        class iterator_c {
[minor] Не очень очевидное название

2020-11-02 11:11 UTC, hazzus commented on signals.h
> +            connection(signal *sig, slot_t slot) noexcept : slot(std::move(slot)), sig(sig) {
Муваешь слот, но принимаешь не по rvalue

2020-11-02 11:11 UTC, hazzus commented on signals.h
> +                if (sig != nullptr) {
Можно внести внутрь `move_connection`, в operator= точно такой же if

2020-11-04 21:48 UTC, FadeevSergey commented on CMakeLists.txt
> +cmake_minimum_required(VERSION 3.13.4)
fixed
Первый вариант ответа: Если есть возможность использовать более старую версию, то почему нет?) Второй вариант ответа: Проверял работоспособность на более старой версии)
Третий вариант ответа: У меня CMake старый())(((

2020-11-04 21:48 UTC, FadeevSergey commented on signals.h
> +        class iterator_c {
Согласен, пофиксил

2020-11-04 21:49 UTC, FadeevSergey commented on signals.h
> +            connection(signal *sig, slot_t slot) noexcept : slot(std::move(slot)), sig(sig) {
Не совсем понимаю что я при этом теряю

2020-11-04 21:49 UTC, FadeevSergey commented on signals.h
> +                if (sig != nullptr) {
Окей, согласен. пофиксил

2020-11-05 03:16 UTC, closed without merging