Зудин Егор M3235
CPP-KT/signal_task pull request #6
Opened 2020-10-25 22:27 UTC by EgorkaZ

2020-10-26 21:47 UTC, hazzus requested changes
Довольно мелкие замечания, но существенные

2020-10-26 21:47 UTC, hazzus commented on signals.h
> +    iteration_token itok(this, m_conns.begin());
Ты же не инициализируешь `iteration_token` никаким другим итератором, кроме `begin`, стоит убрать лишний параметр конструктора

2020-10-26 21:47 UTC, hazzus commented on signals.h
> +        conn.m_sig = nullptr;
Тебе мало занулить `sig` в коннекшене. Инвариант connection подразумевает быть провязанным списком, только когда его сигнал существует.

2020-10-26 21:47 UTC, hazzus commented on signals.h
> +    auto it_toks_end = m_conns.end();
А что если я внутри слота создам `connection`, это точно будет ок, что ты копируешь?

2020-10-26 21:47 UTC, hazzus commented on signals.h
> +        m_sig->m_conns.insert(std::find_if(m_sig->m_conns.begin(), m_sig->m_conns.end(), [&other](const auto & conn) { return &conn == &other; }), *this);
Можно было бы сделать за O(1) если сделать в `intrusive_list` функцию `iterator as_iterator(T& x)`. Вроде делается легко. У тебя так и так там connection в списке лежит. Просто правильно используй свой конструктор `Iterator(list_element<Tag> * element)`

2020-10-26 21:58 UTC, EgorkaZ commented on signals.h
> +    auto it_toks_end = m_conns.end();
К этому конкретному итератору я вообще не обращаюсь, он остался случайно. 

Если речь, о том, что в следующей строчке, то в итераторе `end()` лежит указатель на фейк-ноду `intrusive_list`, так что тут всё должно быть хорошо.
Копирую я здесь для того, чтобы избежать такого сценария:
- в emit'е я вызываю деструктор сигнала, в результате чего все текущие итераторы перебрасываются на `end`
- далее после вызова слота я проверяю, а не стал ли мой итератор равен `end`
- не сделав копию, я обращаюсь к уже удалённому `m_conns` и ловлю UB

2020-10-27 10:13 UTC, hazzus commented on signals.h
> +        conn.m_sig = nullptr;
Ну `disconnect` здесь немного излишен (каждый дисконнект лишний раз итеруется по iteration_tokens). Но я верю, что ты бы исправил.

2020-10-27 10:14 UTC, hazzus commented
Принято

2020-10-27 10:14 UTC, closed without merging